%% SCRIPT PRINCIPAL PARA OPTIMIZACIÓN EN MMS5

PATH.scripts = genpath('scripts');
PATH.data    = genpath('data');
PATH.src     = genpath('src');

structfun(@addpath, PATH)

%% Configuración de fechas

DATES.hist_start = qq(2006, 1);
DATES.hist_end   = qq(2020, 2);
DATES.pred_start = DATES.hist_end + 1;
DATES.pred_end   = DATES.pred_start + 40;

%% Configuración inicial del modelo
MODEL.mod_file_name   = 'mms5.mod';
MODEL.param_file_name = 'setparam.m';
MODEL.data_file_name  = 'data_q.csv';
MODEL.DATES           = DATES;

%% Variables endógenas y exógenas

MODEL.ExoVar = { ...
                    'v_y_star', ...
                    'v_cpi_star', ...
                    'v_fpi', ...
                    'i_star', ...
                    'prem', ...
                    'v_y', ...
                    'v_s', ...
                    'i', ...
                    'E_v_s', ...
                    'v_cpi_nosub' ...
                };
MODEL.EvalVar = {'v_cpi_sub'};

MODEL.NAME = 'MMS5_1_0';

MODEL.LowerLimit = [ ...
    -3.4190, ...'v_y_star'
    0.7198, ...'v_cpi_star'
    -3.8190, ...'v_fpi'
    0.0400, ...'i_star'
    1.5456, ...'prem'
    -1.5456, ...'v_y'
    2.0351, ... 'v_cpi_sub'
    -5.9259 ...'v_s'
];
MODEL.UpperLimit = [ ...
    5.9000, ...'v_y_star'
    3.5863, ...'v_cpi_star'
    5.5853, ...'v_fpi'
    5.3400, ...'i_star'
    5.6674, ...'prem'
    7.0000, ...'v_y'
    10.2026, ...'v_cpi_sub'
    11.5282 ...'v_s'
];

MODEL.x0 = [ ...
    2.5, ...'v_y_star'
    2.0, ...'v_cpi_star'
    0.50, ...'v_fpi'
    2.50, ...'i_star'
    2.50, ...'prem'
    3.50, ...'v_y'
    4, ... 'v_cpi_sub'
    0 ...'v_s'
];

%%

fn = @(x) objective_fn(MODEL, ...
    'ParamAssignValue', x, ...
    'ParamAssignName', { ...
        'v_y_star_ss', ...
        'v_cpi_star_ss', ...
        'v_fpi_ss', ...
        'i_star_ss', ...
        'prem_ss', ...
        'v_y_ss', ...
        'v_cpi_sub_ss', ...
        'v_s_ss' ...
    },...    
    'ParamExtraAssign', { ...
        's.i_ss = s.i_star_ss + s.prem_ss + s.v_s_ss;', ...
        's.v_cpi_nosub_ss = s.v_cpi_ss - s.v_cpi_sub_ss;', ...
        's.v_z_ss = s.v_s_ss + s.v_cpi_star_ss - s.v_cpi_ss;', ...
        's.r_ss = s.i_ss - s.v_cpi_sub_ss;', ...
        's.E_v_s_ss = s.v_s_ss;', ...
        's.E_v_cpi_ss = s.v_cpi_sub_ss;' ...
    }, ...
    'LowerLimit', MODEL.LowerLimit, ...
    'UpperLimit', MODEL.UpperLimit ...
);

%%

MODEL.options = optimset( ...
    'Display', 'iter', ...
    'TolX', 1e-5 ...
    );

MODEL.xmin = fminsearch(fn, MODEL.x0, MODEL.options);
